# 4. The Quest - S&P 500 Stocks Prediction
---
Q2 (ML/DL regression): predpovedajte nastávajúcu situáciu podľa historických dát 4.1

## 4.1 EDA and data preprocessing 	(5b) 
- (A-4b) EDA a data preprocessing pre Vami vybrané charakteristiky z datasetu 
- (B-1b) Zdôvodnite výber ML/DL metód vzhľadom na Vami vybraný dataset pre 4.2
## 4.2 Modeling and evaluation (5b)
- (A-4b) Modeluje Vami tie vybrané charakteristiky pomocou vhodných ML/DL metód. 	Výsledok modelovania je najlepší model.
- (B-1b) Zhodnotíte Váš prístup a získaný výsledok

# 4.1 EDA and data preprocessing

In [23]:
import kagglehub
import pandas as pd
import os

### Načítanie dát

In [24]:
# Download latest version
path = kagglehub.dataset_download("andrewmvd/sp-500-stocks")

print("Path to dataset files:", path)
os.listdir(path)

Path to dataset files: /Users/johanna/.cache/kagglehub/datasets/andrewmvd/sp-500-stocks/versions/1023

['sp500_stocks.csv', 'sp500_companies.csv', 'sp500_index.csv']

In [25]:
df_stocks = pd.read_csv(f"{path}/sp500_stocks.csv")
df_companies = pd.read_csv(f"{path}/sp500_companies.csv")
df_index = pd.read_csv(f"{path}/sp500_index.csv")

### Dataset Stocks

In [26]:
df_stocks.shape

(1891536, 8)

In [27]:
df_stocks.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1891536 entries, 0 to 1891535
Data columns (total 8 columns):
 #   Column     Dtype
---  ------     -----
 0   Date       object
 1   Symbol     object
 2   Adj Close  float64
 3   Close      float64
 4   High       float64
 5   Low        float64
 6   Open       float64
 7   Volume     float64
dtypes: float64(6), object(2)
memory usage: 115.5+ MB

In [28]:
df_stocks.head()

         Date Symbol  Adj Close  Close  High  Low  Open  Volume
0  2010-01-04    MMM        NaN    NaN   NaN  NaN   NaN     NaN
1  2010-01-05    MMM        NaN    NaN   NaN  NaN   NaN     NaN
2  2010-01-06    MMM        NaN    NaN   NaN  NaN   NaN     NaN
3  2010-01-07    MMM        NaN    NaN   NaN  NaN   NaN     NaN
4  2010-01-08    MMM        NaN    NaN   NaN  NaN   NaN     NaN

In [29]:
df_stocks.isnull().sum()

Date               0
Symbol             0
Adj Close    1273705
Close        1273705
High         1273705
Low          1273705
Open         1273705
Volume       1273705
dtype: int64

In [30]:
df_stocks.nunique()

Date           3768
Symbol          502
Adj Close    525360
Close        123637
High         123036
Low          122480
Open         121187
Volume       208513
dtype: int64

In [31]:
df_stocks.describe()

,Adj Close,Close,High,Low,Open,Volume
count,617831.000000,617831.000000,617831.000000,617831.000000,617831.000000,6.178310e+05
mean,79.672357,87.471540,88.417844,86.480997,87.460302,9.347125e+06
std,102.742931,104.521901,105.684113,103.300770,104.519845,4.771669e+07
min,0.203593,0.222000,0.226250,0.216250,0.218000,0.000000e+00
25%,26.572459,32.700001,33.060001,32.299999,32.689999,1.144000e+06
50%,49.821613,59.139999,59.720001,58.500000,59.119999,2.453400e+06
75%,94.831036,105.019997,106.129997,103.889999,105.000000,5.657850e+06
max,1702.530029,1702.530029,1714.750000,1696.900024,1706.400024,3.692928e+09

### Dataset Companies

In [32]:
df_companies.shape

(502, 16)

In [33]:
df_companies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 502 entries, 0 to 501
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Exchange             502 non-null    object
 1   Symbol               502 non-null    object
 2   Shortname            502 non-null    object
 3   Longname             502 non-null    object
 4   Sector               502 non-null    object
 5   Industry             502 non-null    object
 6   Currentprice         502 non-null    float64
 7   Marketcap            502 non-null    int64
 8   Ebitda               473 non-null    float64
 9   Revenuegrowth        499 non-null    float64
 10  City                 502 non-null    object
 11  State                482 non-null    object
 12  Country              502 non-null    object
 13  Fulltimeemployees    493 non-null    float64
 14  Longbusinesssummary  502 non-null    object
 15  Weight               502 non-null    float64
dtypes: float64(5), int64(1), object(10)
memory usage: 62.9+ KB

In [34]:
df_companies.head()

,Exchange,Symbol,Shortname,Longname,Sector,Industry,Currentprice,Marketcap,Ebitda,Revenuegrowth,City,State,Country,Fulltimeemployees,Longbusinesssummary,Weight
0,NMS,AAPL,Apple Inc.,Apple Inc.,Technology,Consumer Electronics,254.49,3846819807232,1.346610e+11,0.061,Cupertino,CA,United States,164000.0,"Apple Inc. designs, manufactures, and markets ...",0.069209
1,NMS,NVDA,NVIDIA Corporation,NVIDIA Corporation,Technology,Semiconductors,134.70,3298803056640,6.118400e+10,1.224,Santa Clara,CA,United States,29600.0,NVIDIA Corporation provides graphics and compu...,0.059350
2,NMS,MSFT,Microsoft Corporation,Microsoft Corporation,Technology,Software - Infrastructure,436.60,3246068596736,1.365520e+11,0.160,Redmond,WA,United States,228000.0,Microsoft Corporation develops and supports so...,0.058401
3,NMS,AMZN,"Amazon.com, Inc.","Amazon.com, Inc.",Consumer Cyclical,Internet Retail,224.92,2365033807872,1.115830e+11,0.110,Seattle,WA,United States,1551000.0,"Amazon.com, Inc. engages in the retail sale of...",0.042550
4,NMS,GOOGL,Alphabet Inc.,Alphabet Inc.,Communication Services,Internet Content & Information,191.41,2351625142272,1.234700e+11,0.151,Mountain View,CA,United States,181269.0,Alphabet Inc. offers various products and plat...,0.042309

In [35]:
df_companies.isnull().sum()

Exchange                0
Symbol                  0
Shortname               0
Longname                0
Sector                  0
Industry                0
Currentprice            0
Marketcap               0
Ebitda                 29
Revenuegrowth           3
City                    0
State                  20
Country                 0
Fulltimeemployees       9
Longbusinesssummary     0
Weight                  0
dtype: int64

In [36]:
df_companies.nunique()

Exchange                 4
Symbol                 502
Shortname              499
Longname               499
Sector                  11
Industry               114
Currentprice           499
Marketcap              502
Ebitda                 469
Revenuegrowth          260
City                   235
State                   41
Country                  8
Fulltimeemployees      387
Longbusinesssummary    499
Weight                 502
dtype: int64

In [37]:
df_companies.describe()

,Currentprice,Marketcap,Ebitda,Revenuegrowth,Fulltimeemployees,Weight
count,502.000000,5.020000e+02,4.730000e+02,499.000000,4.930000e+02,502.000000
mean,217.893685,1.107222e+11,7.045286e+09,0.070541,5.782761e+04,0.001992
std,489.205027,3.440074e+11,1.624213e+10,0.180247,1.395988e+05,0.006189
min,9.400000,4.664099e+09,-3.991000e+09,-0.602000,2.800000e+01,0.000084
25%,68.547500,1.933417e+10,1.625000e+09,0.002000,1.020000e+04,0.000348
50%,118.365000,3.706396e+10,2.952748e+09,0.051000,2.169000e+04,0.000667
75%,227.667500,7.830565e+10,6.020000e+09,0.109000,5.510000e+04,0.001409
max,8276.780000,3.846820e+12,1.495470e+11,1.632000,2.100000e+06,0.069209

### Dataset Index

In [38]:
df_index.shape

(2517, 2)

In [39]:
df_index.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2517 entries, 0 to 2516
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    2517 non-null   object
 1   S&P500  2517 non-null   float64
dtypes: float64(1), object(1)
memory usage: 39.5+ KB

In [40]:
df_index.head()

         Date   S&P500
0  2014-12-22  2078.54
1  2014-12-23  2082.17
2  2014-12-24  2081.88
3  2014-12-26  2088.77
4  2014-12-29  2090.57

In [41]:
df_index.isnull().sum()

Date      0
S&P500    0
dtype: int64

In [42]:
df_index.nunique()

Date      2517
S&P500    2505
dtype: int64

In [43]:
df_index.describe()

            S&P500
count  2517.000000
mean   3346.351605
std    1078.204274
min    1829.080000
25%    2428.370000
50%    2999.910000
75%    4199.120000
max    6090.270000

## 4.1a EDA a data preprocessing pre vybrané charakteristiky z datasetu

## 4.1b Zdôvodnenie výberu ML/DL metód vzhľadom na vybraný dataset pre 4.2

# 4.2 Modeling and evaluation